// Code generated by mockery v2.42.0. DO NOT EDIT.

package mocks_test

import mock "github.com/stretchr/testify/mock"

// MockPlugin is an autogenerated mock type for the Plugin type
type MockPlugin struct {
	mock.Mock
}

type MockPlugin_Expecter struct {
	mock *mock.Mock
}

func (_m *MockPlugin) EXPECT() *MockPlugin_Expecter {
	return &MockPlugin_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function with given fields: args
func (_m *MockPlugin) Execute(args map[string]string) error {
	ret := _m.Called(args)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(map[string]string) error); ok {
		r0 = rf(args)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockPlugin_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type MockPlugin_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - args map[string]string
func (_e *MockPlugin_Expecter) Execute(args interface{}) *MockPlugin_Execute_Call {
	return &MockPlugin_Execute_Call{Call: _e.mock.On("Execute", args)}
}

func (_c *MockPlugin_Execute_Call) Run(run func(args map[string]string)) *MockPlugin_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(map[string]string))
	})
	return _c
}

func (_c *MockPlugin_Execute_Call) Return(_a0 error) *MockPlugin_Execute_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockPlugin_Execute_Call) RunAndReturn(run func(map[string]string) error) *MockPlugin_Execute_Call {
	_c.Call.Return(run)
	return _c
}

// GetExpectedArgs provides a mock function with given fields:
func (_m *MockPlugin) GetExpectedArgs() []string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetExpectedArgs")
	}

	var r0 []string
	if rf, ok := ret.Get(0).(func() []string); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}

	return r0
}

// MockPlugin_GetExpectedArgs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetExpectedArgs'
type MockPlugin_GetExpectedArgs_Call struct {
	*mock.Call
}

// GetExpectedArgs is a helper method to define mock.On call
func (_e *MockPlugin_Expecter) GetExpectedArgs() *MockPlugin_GetExpectedArgs_Call {
	return &MockPlugin_GetExpectedArgs_Call{Call: _e.mock.On("GetExpectedArgs")}
}

func (_c *MockPlugin_GetExpectedArgs_Call) Run(run func()) *MockPlugin_GetExpectedArgs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockPlugin_GetExpectedArgs_Call) Return(_a0 []string) *MockPlugin_GetExpectedArgs_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockPlugin_GetExpectedArgs_Call) RunAndReturn(run func() []string) *MockPlugin_GetExpectedArgs_Call {
	_c.Call.Return(run)
	return _c
}

// GetHelp provides a mock function with given fields:
func (_m *MockPlugin) GetHelp() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetHelp")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// MockPlugin_GetHelp_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetHelp'
type MockPlugin_GetHelp_Call struct {
	*mock.Call
}

// GetHelp is a helper method to define mock.On call
func (_e *MockPlugin_Expecter) GetHelp() *MockPlugin_GetHelp_Call {
	return &MockPlugin_GetHelp_Call{Call: _e.mock.On("GetHelp")}
}

func (_c *MockPlugin_GetHelp_Call) Run(run func()) *MockPlugin_GetHelp_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockPlugin_GetHelp_Call) Return(_a0 string) *MockPlugin_GetHelp_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockPlugin_GetHelp_Call) RunAndReturn(run func() string) *MockPlugin_GetHelp_Call {
	_c.Call.Return(run)
	return _c
}

// GetName provides a mock function with given fields:
func (_m *MockPlugin) GetName() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetName")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// MockPlugin_GetName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetName'
type MockPlugin_GetName_Call struct {
	*mock.Call
}

// GetName is a helper method to define mock.On call
func (_e *MockPlugin_Expecter) GetName() *MockPlugin_GetName_Call {
	return &MockPlugin_GetName_Call{Call: _e.mock.On("GetName")}
}

func (_c *MockPlugin_GetName_Call) Run(run func()) *MockPlugin_GetName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockPlugin_GetName_Call) Return(_a0 string) *MockPlugin_GetName_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockPlugin_GetName_Call) RunAndReturn(run func() string) *MockPlugin_GetName_Call {
	_c.Call.Return(run)
	return _c
}

// Initialize provides a mock function with given fields:
func (_m *MockPlugin) Initialize() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Initialize")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockPlugin_Initialize_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Initialize'
type MockPlugin_Initialize_Call struct {
	*mock.Call
}

// Initialize is a helper method to define mock.On call
func (_e *MockPlugin_Expecter) Initialize() *MockPlugin_Initialize_Call {
	return &MockPlugin_Initialize_Call{Call: _e.mock.On("Initialize")}
}

func (_c *MockPlugin_Initialize_Call) Run(run func()) *MockPlugin_Initialize_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockPlugin_Initialize_Call) Return(_a0 error) *MockPlugin_Initialize_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockPlugin_Initialize_Call) RunAndReturn(run func() error) *MockPlugin_Initialize_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockPlugin creates a new instance of MockPlugin. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPlugin(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPlugin {
	mock := &MockPlugin{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
