name: Release

on:
  push:
    tags:
      - '*'

jobs:
  prepare-pkl-bin:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Download PKL CLI Binary
        run: |
          curl -L -o pkl.bin https://repo1.maven.org/maven2/org/pkl-lang/pkl-cli-linux-amd64/0.25.1/pkl-cli-linux-amd64-0.25.1.bin
          chmod +x pkl.bin

      - name: Set Version Environment Variable
        run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      - name: Prepare PKL Project
        run: |
          echo "Using version $VERSION for packaging"
          ./pkl.bin project package codegen/src/ --output-path out/pkl-package/

      - name: Upload PKL package
        uses: actions/upload-artifact@v3
        with:
          name: pkl-package
          path: out/pkl-package/

  release:
    needs: prepare-pkl-bin
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: pkl-package
          path: out

      - name: Generate release
        uses: marvinpinto/action-automatic-releases@v1.2.1
        with:
          repo_token: ${{ secrets.RELEASE_TOKEN }}
          automatic_release_tag: ${{ github.ref_name }}
          prerelease: false
          files: |
            out/*
